---
name: Deploy
on:
  pull_request_review:
    types: [submitted]

jobs:
  staging:
    name: Build
    runs-on: ubuntu-20.04
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
        
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - name: Deploy to Google Cloud Functions
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'billing-daily-report'
          runtime: 'go116'
          project_id: '${{ secrets.GCP_PROJECT }}'
          entry_point: 'GraphedBilling'
          memory_mb: '128MB'
          region: 'europe-west1'
          event_trigger_resource: 'projects/monom-common-resources/topics/billing-daily-report'
          event_trigger_type: 'google.pubsub.topic.publish'
          env_vars: TABLE_NAME=${{ secrets.TABLE_NAME }},SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }},SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }},GCP_PROJECT=${{ secrets.GCP_PROJECT }}
 